provider = ["rust"]

[phases.setup]
nixPkgs = ["...", "openssl", "wasm-bindgen-cli", "trunk"]
 
[phases.build]
nixLibs = ["trunk"]
cmds = ["trunk build"]

[start]
cmd = "./start.sh"
runImage = "nginx:latest"
onlyIncludeFiles = ["./dist/**/*"]