provider = ["staticfile", "rust"]

[phases.setup]
nixPkgs = ["...", "openssl", "wasm-bindgen-cli", "trunk"]
 
[phases.build]
nixLibs = ["trunk"]
cmds = ["trunk build --dist site"]

[phases.start]
cmd = ""