provider = ["rust"]

[phases.setup]
nixPkgs = ["...", "openssl", "wasm-bindgen-cli", "trunk"]
 
[phases.build]
nixLibs = ["trunk"]
cmds = ["trunk build"]

[start]
cmd = "cp -r dist/* /usr/share/nginx/html"
runImage = "nginx:latest"
onlyIncludeFiles = ['./dist/**/*']